# Generated by Django 5.2.6 on 2025-10-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_folder_document_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
