# Generated by Django 5.2.6 on 2025-10-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_profile_add_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
