# Generated by Django 5.2.6 on 2025-10-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_profile_job_title_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
